### ISSUE TITLE
Update for Nougat

### ISSUE THREAD

**Issue by Sporif** [sylveon/NoEmptyShadeView#1]
On Nougat it's a bit broken, though it still hides the no notifications text the top part with the settings icon and date & time is also hidden.

**Comment by sylveon** [comment]
Yeah I'm seeing it too. I'll see what I can do, but I might need to drop older Android versions since I only have one Nougat device to test.

![](http://b.reich.io/mdvpfu.png)

**Comment by lucas-digital** [comment]
Are you still maintaining this module? Would love to see a working Nougat version :+1:

**Comment by sylveon** [comment]
School got in the way, but since it's Christmas vacations now, I'll try repairing it today

**Comment by sylveon** [comment]
Fixed! ![](https://files.charlesmilette.net/vhRNEO.png)

I'll publish a release right now.
